services:
  # Jenkins用コンテナ
  jenkins:
    build:
      context: ./jenkins
    image: jenkins:test0
    container_name: jenkins-test
    user: root
    ports:
      - "8080:8080"
      - "8000:80"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOST_WORKSPACE: ${PWD}
      JAVA_TOOL_OPTIONS: -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true # JenkinsのGitプラグインがローカルリポジトリを許可するように設定
    restart: unless-stopped

  gitlab:
    # GitLab公式イメージ
    image: gitlab/gitlab-ce:19.4.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        registry_external_url 'http://localhost:5050' # Container Registryの公開URL
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['registry_enabled'] = true
    ports:
      - '8929:8929'
      - '2424:22'
      - '5050:5050'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

  # GitLab CIのRunner
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v19.3.2
    restart: unless-stopped
    network_mode: host
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner'
      - './gitlab/runner-template.toml:/runner-template.toml:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
    profiles:
      - gitlab-ci

  # C++ビルド用コンテナ
  cpp-builder:
    build:
      context: ./builder/cpp
    image: cpp-builder:test0
    working_dir: /workspace
    volumes:
      - .:/workspace
    profiles:
      - tools

  # 静的解析用コンテナ
  cppcheck:
    build:
      context: ./cppcheck
    image: cppcheck:test0
    working_dir: /workspace
    volumes:
      - .:/workspace
    profiles:
      - tools
  
  # vulkanビルド用コンテナ
  vulkan-builder:
    build:
      context: ./builder/vulkan
    image: vulkan-builder:test0
    working_dir: /workspace
    volumes:
      - .:/workspace
    profiles:
      - tools

# Jenkinsのホームディレクトリを永続化するためのボリューム
volumes:
  jenkins_home:
